### PR TITLE
Modifying the path provided for glustereventsd.py

### LINKED ISSUE #15: Path mismatch for glustereventsd.py
The current path of the script file glustereventsd.py is /usr/libexec/glusterfs/gfevents/glustereventsd.py but the path mentioned in the glusterd.fc still points to the old path, this makes the process as unconfined when invoked.

### PR DESCRIPTION
**Pull request by schaffung**
Fixes: #15

Signed-off-by: srijan-sivakumar <ssivakum@redhat.com>

### CODE REVIEW

**Comment by zpytela** [comment]
You can have both the lines in the fc file to support previous versions.

**Comment by schaffung** [comment]
> You can have both the lines in the fc file to support previous versions.

Ack.

**Comment by zpytela** [comment]
OK, I'd just prefer to see it as 1 commit.

**Comment by schaffung** [comment]
I think we can do a squash and merge so that it is taken as one single commit.

**Review by rkothiya — COMMENTED** [review]
LGTM

**Comment by schaffung** [comment]
@wrabcak can you please review the patch ? TIA.

**Comment by wrabcak** [comment]
LGTM.

**Review by wrabcak — APPROVED** [review]

**Pull request merged**
